### ISSUE TITLE
Aaron Murray Info

### ISSUE THREAD

**Issue by amandaharlin** [okcjs/thunderplains-hexo#10]
Speaker
Aaron Murray - Cofounder @ Fractal
![eqzjhvum_400x400](https://cloud.githubusercontent.com/assets/716644/4191487/4b6134e6-378e-11e4-8ebf-74bc8ce52971.png)
## 

Talk
Real World React.js
## 

Bio

Aaron Murray
Hacker, Beatmaker, Taoist, Artist, Architect, Comic nerd 
//
Co-founder @WeAreFractal, @HackingTheTao. 
 Hacker. Beatmaker. Taoist. Comic nerd. Co-org @funcphx @phxbigdata @holiday_js @harvestjs

**Comment by amandaharlin** [comment]
@funkytek get ur 1080hd in here & gimme the deets

**Comment by funkytek** [comment]
React.js brings significant benefits to front-end development: performant virtual DOM diff, one-way data flow and a great component system.  React, however, is just the "V" in MVC, so the question of how to actually architect your application quickly arises. In this talk we will explore using React to build full apps including complementary libs, tooling, pain points and more.  We will touch on the flux pattern and our React-based MV\* implementation.

**Comment by the-simian** [comment]
closed by #14
