### ISSUE TITLE
Name Misspelling

### ISSUE THREAD

**Issue by amandaharlin** [okcjs/thunderplains-hexo#2]
It should be Chris Dickinson, not Dickenson, presenting on Better Living through Control Flow Graph Generation. I misspelled that e, will fix this.

**Comment by amandaharlin** [comment]
Also, Derick Bailey not Dereck Bailey. Gotta fix this one too :facepunch: arg!

**Comment by the-simian** [comment]
In 6th grade I spelled `merriment` as `merryment` in a spelling be, losing it to someone who correctly spelled `adjunct`. Just a year before, I lost an "in class spelling bee" by failing to correctly spell`vacuum` as `vacume`. 
Double "u" diphthongs... drat!!

I knew then, as i know now that this dark shadow would haunt me for all my days, and I would be forever blighted by the pestilence of poor diction and spelling. Here I am, a grown man, and I stand before my 5th and 6th grade class, as they stare accusingly. Just spell the word Jesse. Sound it out. Their dead gaze makes me uneasy as I fumble over the keyboard. Their unaging and eternal faces locked in stone glances with every stroke. The horrors.

Maybe when I finally close this issue. the nightmare shall end. ..maybe.

**Comment by the-simian** [comment]
*Spelling Bee

**Comment by ryoe** [comment]
A typo in a comment about typos. Classic. :smiling_imp:

**Comment by amandaharlin** [comment]
We need to also add in Adam Baldwin from &yet. He's replacing marcy sutton's talk on angular accessibility (she had to cancel this time) & doing a talk on building secure node apps. (He does more infosec + Node.js stuff). @the-simian said he'd fix today, cc @vlucas 4 schedule print outs

**Comment by amandaharlin** [comment]
cc @the-simian chris tweeted at us again. can you update this? and also pick me up from work too?

**Comment by the-simian** [comment]
Yes

**Comment by amandaharlin** [comment]
thank you so, so much. for okcjs stuff i updated the meetup site and made
an email / modified a theme & sent it out

**Comment by the-simian** [comment]
closed by #12

**Comment by amandaharlin** [comment]
hark forth @chrisdickinson so that you may be carbon copied and revel in your appropriately spelled name

**Comment by amandaharlin** [comment]
also can we get your bio, @chrisdickinson? lol
