### ISSUE TITLE
Organize Diversity/Scholorship Ticket Give-Away

### ISSUE THREAD

**Issue by vlucas** [okcjs/thunderplains-hexo#23]
I'd like to give away 4 tickets to ThunderPlains for free. I am hoping @amandaharlin and @campbeja can maybe head this up?

The purpose is to promote diversity, not just in terms of male/female ratio, but in a broader sense to get more people exposed to the conference and the community that might not otherwise have attended or even considered attending. What do you think?

**Comment by amandaharlin** [comment]
I think diversity can also mean people who couldn't have gone otherwise due to cost. If our videos turn out fine people could still watch at home, but there would be networking opportunities that would be missed out on.

**Comment by amandaharlin** [comment]
I think we should contact everyone again, ask if they want to give the ticket away themselves or donate it to a diversity scholarship. If they select the latter we'll handle giving it away for them. We could have a small questionnaire asking potentially interested folk: what are you interested in learning, would attending this conference make an impact in your life, and so on.

**Comment by vlucas** [comment]
That sounds great @amandaharlin - good idea on letting people give their tickets away, too.

I do think there would be some sort of small application process involved since we would have to select people to give the tickets away to, and the words "free" always attract a lot of interest.

**Comment by amandaharlin** [comment]
So email has been sent to remaining tp alums. Already Mike Taylor wrote us back that he'll be using his discount code for his wife. Awesooommee! Glad he responded & that she'll be registered.

**Comment by the-simian** [comment]
:star:  I'm very happy about this :star:

**Comment by vlucas** [comment]
We are nearing just one week away, and we need to better organize this somehow or at least even announce it to get applications. @amandaharlin how are you doing on this?

**Comment by seejessicacode** [comment]
@amandaharlin, let me know how I may help.

On Tue, Sep 30, 2014 at 4:17 PM, Vance Lucas notifications@github.com
wrote:

> We are nearing just one week away, and we need to better organize this
> somehow or at least even announce it to get applications. @amandaharlin
> https://github.com/amandaharlin how are you doing on this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okcjs/thunderplains-hexo/issues/23#issuecomment-57384466
> .

## 

jesslyn.campbell@gmail.com
405.812.7016

**Comment by amandaharlin** [comment]
Thanks @campbeja! 

@vlucas i sent another email recently and there are 7 free tickets left. Elyse tweeted about hers being available & Seb said he'd ask around his SF community, Jeremy had someone in mind to give his away to, Rob gave his to @gitOfi, but the others haven't responded. I'm not quite sure how to reach more women, I posted about the tickets in the code club forums but only one person has taken a ticket. I'd also like anyone apply for the diversity tickets too. 

How else do you think we should find people?

**Comment by vlucas** [comment]
We have a mailing list for okcjs! We can create a quick announcement with a link to the applciation, and just have text in there like "please forward this on to anyone you can think of who would attend if they were given the opportunity with a free ticket", etc. We will get the word out! :)

**Comment by amandaharlin** [comment]
+1 +1 +1 +1 great thinking @vlucas!

**Comment by amandaharlin** [comment]
our application can just be a google doc asking for their name, email, and how they heard about thunder plains. 

this might be too much to ask for, but i wouldn't mind asking if they thought techlahoma events have helped them as a developer or if they think it attending them in the future would.

**Comment by seejessicacode** [comment]
I just made a quick google form for a possible outline: http://goo.gl/forms/L6D1npj1iD

**Comment by seejessicacode** [comment]
This form is only visible to those with the link.

**Comment by amandaharlin** [comment]
Great job! I sent out a form yesterday too, lol. https://docs.google.com/forms/d/1dbe7-UHdFzqX9HaEiS3eea6RNhRmwkxMgVGFHpqoue0/viewform?c=0&w=1 I think we should combine these: I like that you asked about the okcjs mailing list and what they hoped to learn but I'd take out the age because we don't really need to know that.

**Comment by seejessicacode** [comment]
Looks great!

On Wed, Oct 1, 2014 at 8:43 AM, Amanda Harlin notifications@github.com
wrote:

> Great job! I sent out a form yesterday too, lol.
> https://docs.google.com/forms/d/1dbe7-UHdFzqX9HaEiS3eea6RNhRmwkxMgVGFHpqoue0/viewform?c=0&w=1
> I think we should combine these: I like that you asked about the okcjs
> mailing list and what they hoped to learn but I'd take out the age because
> we don't really need to know that.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/okcjs/thunderplains-hexo/issues/23#issuecomment-57464567
> .

## 

jesslyn.campbell@gmail.com
405.812.7016

**Comment by amandaharlin** [comment]
Power of teamwork!! ♡

**Comment by amandaharlin** [comment]
so with the amount of sold tickets (subtracting the speakers) we have 32 more tickets available according to the current ticket limit.

if that number factors in the diversity tickets, it would leave us at 25 left to purchase.

(I've got a friend who volunteered to help. we could give her one of the diversity tickets or make a volunteer code. that would make 6 tickets diversity then.)

p kewl news!

**Comment by vlucas** [comment]
You bring up a good point with the diversity tickets. I will subtract 6
from the total upper limit so that we won't oversell once the diversity
tickets are accounted for.

## 

Vance Lucas
http://vancelucas.com
(405) 303-1021

**Comment by amandaharlin** [comment]
So i need to register @carmalou for a diversity ticket. she might have an interested coworker that could use the last diversity ticket, which would mean all of our scholarship tickets were used! ~yay!~ 

(this is just a mental note to do this.)

**Comment by amandaharlin** [comment]
ok gotta register carmen & her coworker which means opening up the tickets to get their discount codes in. guess i'll do this tonight

**Comment by the-simian** [comment]
Thank you
