### ISSUE TITLE
Book Catering for Afterparty

### ISSUE THREAD

**Issue by vlucas** [okcjs/thunderplains-hexo#26]
We still need to book catering for the after party. The Paramount is totally cool with outside companies doing this at no additional charge from them.

**Comment by amandaharlin** [comment]
Want to do tacos and nachos again or try something else? :-)

**Comment by vlucas** [comment]
Yes. Taco/nacho bar for the win!

**Comment by vlucas** [comment]
Last year we used Yucatan Taco Stand and paid $460.00 for the food. We also spent $300 on drinks. We had a _LOT_ of leftovers last year though too...

**Comment by vlucas** [comment]
Catering is **booked**! I spoke with Lynn, an owner of Yucatan Taco Stand and he agreed to give us a combination taco/nacho bar with all the fixings, plus plates, napkins, utensils, etc. for 100-125 people for $1,000. The will arrive at the Paramount at 6:00pm to setup. This is roughly double what we has last year, so the pricing is in-line with what they gave us the previous year, and this year we get a little bit more stuff.

**Comment by amandaharlin** [comment]
omg @vlucas!!!!! yes!

**Comment by the-simian** [comment]
:+1: :us: :us: :us: :us: :us: :us: :us: :us:
