### ISSUE TITLE
Volunteer roundup/pregame

### ISSUE THREAD

**Issue by the-simian** [okcjs/thunderplains-hexo#28]
Compile a definitive list of volunteers. Contact them. Meet up for a dinner _before_ the actual speaker's dinner.

**Comment by DevinClark** [comment]
_raises hand_

**Comment by amandaharlin** [comment]
Just talked to @coriebreaux & she wants to volunteer

**Comment by the-simian** [comment]
Joe Donley agreed to take photos at the event.

**Comment by amandaharlin** [comment]
Things for volunteers to do:
- help with registration and check in (be there early)
- watch for misconduct and alert organizers to it
- tweet photos and promote the conference and our community online
- scan the mentions to @thunderplains and look for any misconduct or requests for help/assistance
- check in on speakers to make sure they're doing well or need anything (internet connectivity problems, drinks, food, electronic failures, etc)
- instruct attendees on where the registration, lunch and restrooms are located
- guide/assist attendees to the after party at the paramount. Make sure visitors move in a herd to avoid getting lost.
- watch for non-thunder plains attendees entering Into the conference rooms and lunch rooms. (since we are so very close to selling out tickets, it would be wrong to let an innotech (or otherwise non-thunder plains) attendee take an already reserved seat. There should be no persons forced to stand due to lack of seats. Every attendee had a paid for seat so they are right to expect a chair or accessible place.)

**Comment by amandaharlin** [comment]
Jessica and I already put together the care packages and some day-of snacks.

**Comment by CaptainYarb** [comment]
I would love to help out with anything I can. I can be there early and late.

**Comment by jwdonley** [comment]
Hello, at some point in the next day or so I'd like to have a conversation with someone on some photography logistics.

**Comment by amandaharlin** [comment]
Thank you @joedonley!

Are we doing a volunteer (potluck) get-together?

Oh hey we can meet up online or at the library in OU (on their bottom floor
they have this swanky coworking space & a cafe & meeting rooms -- like
~fancy~ rooms and regular rooms)

**Comment by DevinClark** [comment]
@amandaharlin I like the idea of meeting there. I'd be interested to hear what ~fancy~ rooms are and how they compare to regular rooms. :tangerine:

**Comment by amandaharlin** [comment]
lol for a preview, check out their twitter feed 4 photos ~
https://twitter.com/OULibHCLC ~_~_~_~_

**Comment by vlucas** [comment]
We could also all meet up at a restaurant or something.

**Comment by amandaharlin** [comment]
Ooooh yeah that's a good idea. Want to meet up in OKC? That might be less
of a drive for Vance. We could go to go go sushi or somewhere else :P

**Comment by vlucas** [comment]
We could meetup anywhere around OKC - Norman and Moore are fine too. Honestly they all take around the same time to get to from Shawnee.

**Comment by amandaharlin** [comment]
That's good to know. Sorry about your commute! thanks for taking it in such
strides! :-(

**Comment by amandaharlin** [comment]
Ok, ideas for a restaurant? @campbeja @jdonley83 @the-simian @DevinClark @vantreeseba? 

all i'm coming up with is panera, lol

**Comment by mkchandler** [comment]
I talked to @the-simian today about volunteering, so count me in

**Comment by amandaharlin** [comment]
yay!!! :sparkling_heart:

**Comment by amandaharlin** [comment]
oh, @blazedd! sorry i didn't see your comment earlier. you're in, thanks for volunteering!

**Comment by mkchandler** [comment]
Not sure if I will be able to attend a volunteer meetup beforehand though because my schedule is booked up the next couple nights :-(

**Comment by amandaharlin** [comment]
@campbeja will you be heading out before the dinner? we'd love to have you & collin, but totally understand if you guys need to get on the road sooner.

**Comment by amandaharlin** [comment]
@mkchandler that's totally ok, we'll just be giving out tshirts, going over the CoC, talking about tasks to do & where restrooms & exits are. we'll just catch you up the morning of.

**Comment by amandaharlin** [comment]
volunteer list:

@DevinClark 
@coriebreaux (will be at dinner & day-of)
@jdonley83 (photog ~ finally we'll get some photos! yay!)
@mkchandler (will be there day of, unlikely to be at volunteer dinners)
@blazedd 
@campbeja (likely to be at volunteer dinner, but is on vacation day-of)
(+ organizers)

i'm guessing also likely volunteers are dennis ferron, ben van treese, @jagthedrummer. :sparkles:

**Comment by seejessicacode** [comment]
The Mrs. and I won't be heading out until Thursday morning, so count me in. I can't speak for the Mrs. til I get home.

**Comment by amandaharlin** [comment]
yay! @campbeja :space_invader: no worries if y'all end up not going, just wanted to make sure you knew we want you guys to be a part of this! :sparkles:

**Comment by amandaharlin** [comment]
when should this pre-dinner-dinner be? tuesday i guess? lol if you can't make it to this we'll just go over details through email, wed night, or thurs morning.

**Comment by amandaharlin** [comment]
omg i'm so excited! we're a great team!

**Comment by jagthedrummer** [comment]
I'm happy to help any way that I can when I'm not either delivering my talk or frantically changing my slides at the last minute. :)

**Comment by amandaharlin** [comment]
OH wait you're also a speaker, sorry! let us know if you'd care for any slide reviews before your talk. we're sure it'll be great, but if you need us we're here.

**Comment by jagthedrummer** [comment]
Thanks!

**Comment by CaptainYarb** [comment]
@amandaharlin no worries. I'm here to help if and when needed. I've got a fairly open schedule, but as I share a car with my SO I'll need a little heads up for any time changes to help me coordinate the car.

**Comment by amandaharlin** [comment]
thanks for the heads up! we'll try to give you more time in advance. :+1:

**Comment by thirdcreed** [comment]
oo oo me me

**Comment by amandaharlin** [comment]
omg yay @thirdcreed!!!!!!!!!!!!!!!!! :sparkles: :sparkles: :sparkles: :sparkles: :sparkles:

**Comment by vlucas** [comment]
Okay, we need to start talking times. How about 6 or 7pm tomorrow for a "volunteer dinner" to settle all the assingments?

**Comment by CaptainYarb** [comment]
That is ideal for me. +1

**Comment by amandaharlin** [comment]
:+1: that time is fine with me :)

**Comment by CaptainYarb** [comment]
http://nhinja.com/ Is a great Sushi place that has several locations, however not near downtime. Very clean and relaxed meeting friendly.

**Comment by jwdonley** [comment]
any way I could just skype or google hangout in? I'm down in Chickasha and am on kid duty all day since the wife has class until late evening. I really just need about a 5 minute convo with someone right quick

**Comment by vantreeseba** [comment]
LEMME KNOW WHAT TO DO I CAN DO IT.

**Comment by amandaharlin** [comment]
Joe, that's totally fine! Please let Alex skype tooooo~

Ben, ty! =^__^=

**Comment by GJBranch** [comment]
I'll volunteer.

**Comment by vlucas** [comment]
Okay, we need to set the meeting place/time so we can plan this for today. We need a place that is not loud so we can all talk. Also it looks like we will have up  to 10-12 people, so a good amount of space or a back room would be nice too. Know anywhere in OKC/Norman/Moore that fits the bill?

**Comment by amandaharlin** [comment]
we could meet at the 404?

**Comment by amandaharlin** [comment]
credit goes to @datachomp for that! :sparkles:

**Comment by vlucas** [comment]
Yeah we could either order food and meet somewhere like the 404 in OKC, or we could find a quiet restaurant like maybe IHOP in bricktown. Either one is cool with me. If we do the 404, I guess we could get Joey's pizza.

**Comment by amandaharlin** [comment]
i'd be down with that! it'd be cool to involve them in on this in some way,
even if it's just being a place where we meet.

panera (at least in s okc) has a back room that we could use (i think the
infosec groups used to meet there).

there's a place called Blu in norman and the good egg / good dining group
restaurants might also be good choices.

**Comment by the-simian** [comment]
Joeys/404 seems good, since its central to everyone. is 7:00pm okay with everyone else?

**Comment by CaptainYarb** [comment]
That works for me

**Comment by vlucas** [comment]
7:00pm works for me. Let's do eeet.

**Comment by amandaharlin** [comment]
yay!!!

**Comment by amandaharlin** [comment]
[joey's pizzeria menu](http://www.joeyspizzeriaokc.com/menu.html) we can place an order early if you want ~

**Comment by the-simian** [comment]
Awesome, this is all great news.

**Comment by amandaharlin** [comment]
@dennisferron is missing the volunteers dinner but will be volunteering day-of

**Comment by seejessicacode** [comment]
Will anyone be at the 404 early? I'll just hang out late at the office if not.

**Comment by the-simian** [comment]
we might be a little early. We're stashing some afterparty food.

**Comment by amandaharlin** [comment]
We're heading over to the 404 from norman. Ordered some pizzas from joey's. if you're there at 7 pm feel free to head over and grab some slices :pizza:

**Comment by mkchandler** [comment]
Sorry I couldn't make it tonight. I can be there early on Thursday, so just
let me know what you want me to do :-)

**Comment by amandaharlin** [comment]
Oh it's totally fine! Thanks for all your help & support ~_~_ glad you got
your prototek card too!

**Comment by drinkgreen** [comment]
I've been talking via Twitter with @amandaharlin about volunteering but I forgot to actually say it here.  If you still have a spot open I would like to help.

**Comment by drinkgreen** [comment]
I'm @travisleeb on Twitter btw

**Comment by vlucas** [comment]
We plan on showing up to the Cox center between 7:00am - 7:30am Thursday the day of the event.

**Comment by mkchandler** [comment]
Sounds good @vlucas. I will be there at 7:00 AM.

**Comment by drinkgreen** [comment]
I have jinxed myself undoubtedly.  I have an emergency project release due out tomorrow so I will have to not only back out of volunteering but out of Thunder Plains itself. 

Sorry for the inconvenience,
Travis Benham

**Comment by vlucas** [comment]
@drinkgreen if you have already purchased a ticket, you should consider giving it away to someone else via Twitter, etc. There were a few people who were looking for tickets that were too late in purchasing one before we sold out.

**Comment by matthewreily** [comment]
I'll be there at 7:00

-----Original Message-----

**Comment by CaptainYarb** [comment]
I'll be there at 7:00

**Comment by DevinClark** [comment]
I'll be there at 6:59.

**Comment by vlucas** [comment]
Haha, way to one-up those other schmucks, @DevinClark!

**Comment by jwdonley** [comment]
I'll be there at 7:00 as well. Also, the photo gallery that will be updated during the day will be at: http://joethephotographyguy.com/thunder-plains/

**Comment by drinkgreen** [comment]
I'm back in!  I can't make 7am though so I'll be looking more at 7:30am. 

Travis

**Comment by MarkWissler** [comment]
Hey all, sorry I missed this whole thread. I'll be around all day tomorrow, if anyone has any random tasks or whatever, let me know! @MarkWissler on twitter, or Jesse has my phone#. I'm especially good at carrying heavy things :meat_on_bone: Otherwise, I'll just be trying to make myself generally helpful.

See you all tomorrow!

**Comment by mkchandler** [comment]
Are we meeting in front of the Thunder Plains rooms?

**Comment by CaptainYarb** [comment]
I'm not the only confused one

**Comment by CaptainYarb** [comment]
We are waiting at the reception near the rooms

**Comment by drinkgreen** [comment]
Ugh.  Had trouble getting kid out the door for school.  En route now though!

**Comment by the-simian** [comment]
Thank you everyone!
