### ISSUE TITLE
Determine Afterparty Location

### ISSUE THREAD

**Issue by vlucas** [okcjs/thunderplains-hexo#4]
- We are planning on **6:30pm - 10:30pm**, so plan for 4 hours
- Volunteers will help walk people over from the Cox Center

**Comment by vlucas** [comment]
Paramount OKC:
**$100/hr**
- Needs 30 days notice
- Can bring any food+drinks we want at no additional cost except alcoholic
- Can access the space up to 1hr early for setup
- Full bar is offered by Paramount (can be paid open bar or cash bar) - we can also buy _n_ amount of tickets and hand them out, then cash bar after that

**Comment by vlucas** [comment]
I think @JesseHarlin is calling the IAO. Just post the details here when you do that.

**Comment by amandaharlin** [comment]
With the Paramount, can we access the space upstairs? I thought they opened it up recently... It sounds nice! // The IAO didn't answer their phones, but I sent them an email. // Also, we could do the after party at the museum of art, but film row seems like the most likely candidate.

**Comment by vlucas** [comment]
Yes - the paramount event space is upstairs, and they do have availability on Oct. 9th.

**Comment by amandaharlin** [comment]
That sounds good. I'm pretty sold on using them.

**Comment by vlucas** [comment]
Honestly I think the Paramount is going to be far more cost efficient than any other space. Just the fact that they will let us bring our own food and drink is going to save us a ton.

Plus the place is pretty cool, has coffee downstairs, etc.

**Comment by amandaharlin** [comment]
@JesseHarlin said he's good with using the paramount too. :-)

**Comment by vlucas** [comment]
I reserved the Paramount on Thursday 9/11 with a $200 deposit. We can decide if we want to do drink tickets for everyone a bit closer to the event - that option is available and the tickets could also be used for coffees and other drinks besides alcoholic ones.

**Comment by amandaharlin** [comment]
+1 +1 +1 fantastic job getting that done!

**Comment by the-simian** [comment]
Thanks!
