### ISSUE TITLE
Get esimates on t-shirt prices

### ISSUE THREAD

**Issue by vlucas** [okcjs/thunderplains-hexo#5]
We need to get prices on t-shirts for ThunderPlains
- Estimate for 250 shirts
- We need more L and XL shirts than the normal distribution (and possibly a few more XXL ones as well)

**Comment by amandaharlin** [comment]
On ticketbud did we ask what size of shit they'd like? I remember last year running out of a lot of smalls and extra-smalls. Thank you for handling the tshirts! You go Vance! :sparkles:

**Comment by vlucas** [comment]
Done, and shirts will be ordered by today.

**Comment by amandaharlin** [comment]
:clap: :+1: :chart_with_upwards_trend: great job Vance!

**Comment by the-simian** [comment]
:rocket:
