### ISSUE TITLE
Volunteer/Speaker Dinner

### ISSUE THREAD

**Issue by amandaharlin** [okcjs/thunderplains-hexo#6]
Do we want to have our get together at Red Pin? (Red Pin did work really well for us for atmosphere, food & entertainment.) If we want to change, alternatives could be the 404 or Dunlap Codding with Joey's or other downtown food.

**Comment by vlucas** [comment]
I am thinking we do the speaker/volunteer dinner this year at KD's restaurant in Bricktown.

**Comment by amandaharlin** [comment]
Oh that's a super neat idea! Southern cuisine +1

**Comment by the-simian** [comment]
:+1:
