### ISSUE TITLE
Adam Baldwin Info

### ISSUE THREAD

**Issue by amandaharlin** [okcjs/thunderplains-hexo#8]
Speaker
Adam Baldwin - Chief Security Officer/Director de Seguridad @ &andyet 

![baldwin2](https://cloud.githubusercontent.com/assets/716644/4191239/e91d4f10-378b-11e4-81a5-703946a806b3.jpg)
## 

Talk Abstract

Node.js security live

For years developers have been told to think about and bake security into their apps while they code for various reasons. 

This talk will explore this old adage and see just how it might play out, live.

As a web application is built we will explore when is the right time to think about security controls like authentication, authorization, security headers and many more and what can happen if those are ignored.
## 

Bio [src = &yet bio](https://andyet.com/team/baldwin)

The BBS owner, having discovered that some kid had brute-forced his passwords for funsies, declined to press charges against Adam, and instead did the next best thing: offered him a job. Under that long-ago sensei’s tutelage, Adam learned the ways of hacking and of reverse engineering, awakening a love for breaking things.

Adam is adept in assessing and securing Node.js, Ruby on Rails, Django, and PHP web apps, as well as providing expertise on secure application design and performing penetration testing at key project points prior to and after launch.

When he’s not experiencing the beauty of winning, Adam is spending time with his equally lovely family and giving speeches on web security at like all the conferences ever.

**Comment by amandaharlin** [comment]
cc @evilpacket ~ is the photo & bio ok with you? :spaghetti:

**Comment by evilpacket** [comment]
I looked at a few of the other talks and the bio's are really just talk abstracts. Would you rather me put something like that together for the site? Might work better than my long bio... picture is fine.

**Comment by amandaharlin** [comment]
That would be fine. What about this? Your bio is so neat that i don't want to cut too much!

Adam entered the world of hacking way back when he was a wee slip of a lad. Because when you live in a town whose major pastimes are farming and gossip, breaking into a BBS can seem like great fun. Right up until you get caught. Which he did.

The BBS owner, having discovered that some kid had brute-forced his passwords for funsies, declined to press charges against Adam, and instead did the next best thing: offered him a job. Under that long-ago sensei’s tutelage, Adam learned the ways of hacking and of reverse engineering, awakening a love for breaking things. 

Adam is adept in assessing and securing Node.js, Ruby on Rails, Django, and PHP web apps, as well as providing expertise on secure application design and performing penetration testing at key project points prior to and after launch.

When he’s not experiencing the beauty of winning, Adam is spending time with his equally lovely family and giving speeches on web security at like all the conferences ever.

**Comment by evilpacket** [comment]
Works for me :)

**Comment by amandaharlin** [comment]
:sparkles: awesome!

**Comment by the-simian** [comment]
Thanks for getting all this up!

**Comment by vlucas** [comment]
I hate to crash the party, but I actually think we do need a real talk abstract. We are going to be printing the talk schedules with abstracts, and these abstracts are important because they help people decide which talks to attend. So while your bio is undoubtedly cool, would you mind throwing together a talk abstract for us? We have to get the print stuff together ASAP, so the sooner the better! :)

**Comment by evilpacket** [comment]
No worries, it's kind of what I was thinking by looking at other talks.
I'll try and put something together tomorrow. I don't have the concept
done completely but I can still put something together that will work
even with some changes.

Vance Lucas wrote:

**Comment by evilpacket** [comment]
Sent my abstract to Amanda. I could put it here too I suppose. Let me know what I should do. I'm in another timezone right now and my brain is kind of mush. ha

**Comment by amandaharlin** [comment]
Oh, no, you're fine! I updated the op with your abstract and we'll update
the site soon. Enjoy instructing the security classes, we'll try not to
bother you during it. :-)

**Comment by vlucas** [comment]
The new abstract looks good. We'll get it up soon. :+1:

**Comment by the-simian** [comment]
closed by #12
