### ISSUE TITLE
Eric Schoffstall Info

### ISSUE THREAD

**Issue by amandaharlin** [okcjs/thunderplains-hexo#9]
Speaker
Eric Schoffstall - Cofounder @ Fractal
![e421e88e9248d199ac126fb56941b0e3](https://cloud.githubusercontent.com/assets/716644/4191389/6d0dccc2-378d-11e4-9ea6-7d3c89156a02.jpeg)
## 

Talk
## Genome.js

Bio
I experience life through code and have way too many hobbies. I live to travel.

**Comment by amandaharlin** [comment]
cc @contra ~ gimme ur deets

**Comment by yocontra** [comment]
Abstract:

Genetics: the final frontier. What is the link between the human genome and Javascript? Do you want to find out why your body does that weird thing? In this talk we will unravel the mystery surrounding your source code, and explore using Javascript to make sense of it. Included with your ticket is a copy of my genome which you may use to make clones.

Let me know if you need anything else

**Comment by the-simian** [comment]
Thanks, this is good!

**Comment by the-simian** [comment]
closed by #14
